ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG_M/ G

     

      DOUBLE PRECISION MT,MW,MZ,MTA,MB,MX2
     $ ,MH

      COMMON/MASSES_M/ MT,MW,MZ,MTA,MB,MX2,MH


      DOUBLE PRECISION WZ,WX2,WH,WW,WT

      COMMON/WIDTHS_M/ WZ,WX2,WH,WW,WT


      DOUBLE COMPLEX GC_6, GC_7, GC_8, GC_10, GC_11, GC_1, GC_2, GC_26
     $ , GC_27, GC_29, GC_30, GC_39, GC_40, GC_42, GC_43, GC_46, GC_48
     $ , GC_49, GC_56, GC_57, GC_59, GC_60, GC_9, GC_12, GC_13, GC_14,
     $  GC_15, GC_16

      COMMON/COUPLINGS_M/ GC_6, GC_7, GC_8, GC_10, GC_11, GC_1, GC_2,
     $  GC_26, GC_27, GC_29, GC_30, GC_39, GC_40, GC_42, GC_43, GC_46,
     $  GC_48, GC_49, GC_56, GC_57, GC_59, GC_60, GC_9, GC_12, GC_13,
     $  GC_14, GC_15, GC_16

